version: '3.8'
name: task-flow
services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    networks:
      - task-flow-network
    command: redis-server --appendonly yes

networks:
  task-flow-network:
    driver: bridge
